# Generated by Django 2.2.3 on 2019-07-10 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetName', models.CharField(max_length=128, unique=True)),
                ('assetId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskDescription', models.CharField(max_length=128, unique=True)),
                ('taskId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workerName', models.CharField(max_length=128, unique=True)),
                ('workerId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfAllocation', models.DateField()),
                ('taskToBePerformedBy', models.DateField()),
                ('_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HK_APIs.Asset')),
                ('_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HK_APIs.Task')),
                ('_worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HK_APIs.Worker')),
            ],
        ),
    ]
