# Generated by Django 2.2.3 on 2019-07-10 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HK_APIs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskallocation',
            name='taskToBePerformedBy',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='taskallocation',
            name='timeOfAllocation',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
